spring:
  cloud:
    gateway:
      enabled: true
      routes:
      - id: route1
        uri: http://localhost:9000
        predicates:
        - Path=/hello
management:
  endpoints:
    web:
      exposure:
        include: "*"